# Generated by Django 5.2.4 on 2025-07-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Chocolate', 'Chocolate'), ('Candy', 'Candy'), ('Pastry', 'Pastry'), ('Nut-Based', 'Nut-Based'), ('Milk-Based', 'Milk-Based'), ('Vegetable-Based', 'Vegetable-Based')], max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
